.TH gplib 1 "(c) 2002, 2003, 2004, 2005 Craig Franklin"

.SH NOM
gplib - Bibliothécaire GNU PIC

.SH SYNOPSIS
.B gplib [options] bibliothèque [membre]

.SH AVERTISSEMENT
Les informations de cette page de manuel sont extraites de la documentation 
complète de gputils et sont limitées à la signification des options. Pour une 
documentation complète, reportez-vous au fichier «\ gputils.ps\ » (en anglais) 
situé dans le répertoire doc de gputils.

.SH DESCRIPTION
.B gplib
crée, modifie et extrait des archives COFF pour les microcontrôleurs PIC (TM)
de Microchip (TM).
.B gplib
est une partie de gputils. Consultez la page manuel gputils(1) pour avoir
des détails sur les autres utilitaires GNU PIC.

.SH OPTIONS
.TP
.B -c, --create
Créer une nouvelle bibliothèque.
.TP
.B -d, --delete
Supprimer «\ membre\ » de «\ bibliothèque\ ».
.TP
.B -h, --help
Afficher un message d'usage.
.TP
.B -n, --no-index
Ne pas ajouter l'index des symboles.
.TP
.B -q, --quiet
Mode silencieux.
.TP
.B -r, --replace
Ajouter ou remplacer «\ membre\ » de «\ bibliothèque\ ».
.TP
.B -s, --symbols
Afficher les symboles globaux de «\ bibliothèque\ ».
.TP
.B -t, --list
Afficher les membres de «\ bibliothèque\ ».
.TP
.B -v, --version
Afficher la version.
.TP
.B -x, --extract
Extraire «\ membre\ » de «\ bibliothèque\ ».

.SH VOIR AUSSI
gputils(1)

.SH AUTEUR
Craig Franklin <craigfranklin@users.sourceforge.net>

.SH TRADUCTION
.PP
Ce document est une traduction réalisée par Alain Portal
<aportal AT univ-montp2 DOT fr> le 14 octobre 2004 et révisée
le 24 mai 2005.
.PP
L'équipe de traduction a fait le maximum pour réaliser une adaptation
française de qualité. La version anglaise la plus à jour de ce document est
toujours consultable via la commande\ : «\ \fBLANG=en\ man\ 1\ gplib\fR\ ».
N'hésitez pas à signaler à l'auteur ou au traducteur, selon le cas, toute
erreur dans cette page de manuel.

.SH COPYRIGHT
Copyright (C) 2002, 2003, 2004, 2005 Craig Franklin

Ce programme est un logiciel libre\ ; vous pouvez le redistribuer et/ou le
modifier sous les termes de la licence GNU GPL telle que publiée par la Free
Software Foundation\ ; soit la version 2, soit (à votre convenance) toute
version ultérieure.

Ce programme est distribué dans l'espoir qu'il soit utile, mais
SANS AUCUNE GARANTIE\ ; même sans la garantie implicite d'UTILISABILITÉ
ou d'ADAPTATION À UN USAGE PRÉCIS. Lisez la licence GNU GPL pour plus
de détails.

Vous devriez avoir reçu une copie de la licence GNU GPL avec ce programme\ ;
si ce n'est pas le cas, écrivez à Free Software Foundation, Inc., 675 Mass Ave,
Cambridge, MA 02139, USA.
