.TH gpstrip 1 "(c) 2005 Craig Franklin"
.SH NAME
gpstrip - discard symbols from object file
.SH SYNOPSIS
.B gpstrip [options] [file(s)]
.SH WARNING
The information in this man page is an extract from the full documentation of
gputils and is limited to the meaning of the options.  For complete and 
current documentation, refer to "gputils.ps" located in the gputils docs 
directory.
.SH DESCRIPTION
.B gpstrip
discards symbols from GNU PIC object files.
.B gpstrip
is part of gputils.  Check the gputils(1) manpage for details on other GNU 
PIC utilities.
.SH OPTIONS
.TP
.B -g, --strip-debug
Strip debug symbols. 
.TP
.B -h, --help
Show this usage message. 
.TP
.B -k SYMBOL, --keep-symbol SYMBOL
Keep symbol. 
.TP
.B -n SYMBOL, --strip-symbol SYMBOL
Remove symbol. 
.TP
.B -o FILE, --output FILE
Alternate name of output file. 
.TP
.B -p, --preserve-dates
Preserve dates. 
.TP
.B -r SECTION, --remove-section SECTION
Remove section. 
.TP
.B -s, --strip-all
Remove all symbols. 
.TP
.B -u, --strip-unneeded
Strip symbols not need for relocations. 
.TP
.B -v, --version
Show version. 
.TP
.B -x, --discard-all
Remove non-global symbols. 
.SH SEE ALSO
gputils(1)
.SH AUTHOR
Craig Franklin <craigfranklin@users.sourceforge.net>
.SH COPYRIGHT
Copyright (C) 2005 Craig Franklin

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
