.TH gputils 1 "(c) 2002, 2003, 2004, 2005 James Bowman, Craig Franklin"
.SH NAME
gputils - GNU PIC Utilities
.SH DESCRIPTION
.B gputils
is a collection of development tools for Microchip (TM) PIC (TM) 
microcontrollers. It's intended to be compatible with the manufacturer's 
tools, MPASM, MPLINK,and MPLIB.
.SH SEE ALSO
gpasm(1), gpdasm(1), gplib(1), gplink(1), gpstrip(1), gpvc(1), gpvo(1)
.SH AUTHOR
Craig Franklin <craigfranklin@users.sourceforge.net>
.SH COPYRIGHT
Copyright (C) 2002, 2003, 2004, 2005 James Bowman, Craig Franklin

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
